### create transfer
POST http://localhost:8080/transfers
Content-Type: application/json
Authorization: Bearer {{$dotenv HTTP_ACCESS_TOKEN}}

{
  "from_account_id": 1,
  "to_account_id": 2,
  "currency": "USD",
  "amount": 10
}

### fail to transfer because invalid currency
POST http://localhost:8080/transfers
Content-Type: application/json
Authorization: Bearer {{$dotenv HTTP_ACCESS_TOKEN}}

{
  "from_account_id": 1,
  "to_account_id": 2,
  "currency": "ZZZ",
  "amount": 10
}